spring:
  profiles:
    default: local
    group:
      local: local,secret

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false  # OSIV 설정 중요

management:
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: /actuator
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: never
      show-components: always

# 채팅(stomp) 설정
chat:
  message: # 메시지 수 제한
    max-length: 500
    min-length: 1

social:
  kakao:
    audience: 18af8def9522316a9c30d75d997df2b1
  apple:
    audience: com.rosyocean.debateseason
