spring:
  profiles:
    default: local
    group:
      local: local,secret

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false  # OSIV 설정 중요

management:
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: /actuator
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: never
      show-components: always

social:
  kakao:
    audience: "your-kakao-client-id"
    issuer: "https://kauth.kakao.com"
    jwksUrl: "https://kauth.kakao.com/.well-known/jwks.json"
  apple:
    audience: "your-apple-client-id"
    issuer: "https://appleid.apple.com"
    jwksUrl: "https://appleid.apple.com/auth/keys"

# 채팅(stomp) 설정
chat:
  message: # 메시지 수 제한
    max-length: 500
    min-length: 1