INSERT INTO community (name, icon_url)
VALUES ('디시인사이드', 'community/icons/dcinside.png'),
       ('에펨코리아', 'community/icons/fmkorea.png'),
       ('더쿠', 'community/icons/theqoo.png'),
       ('뽐뿌', 'community/icons/ppomppu.png'),
       ('루리웹', 'community/icons/ruliweb.png'),
       ('엠팍', 'community/icons/mlbpark.png'),
       ('인벤', 'community/icons/inven.png'),
       ('네이트 판', 'community/icons/natepann.png'),
       ('아카라이브', 'community/icons/arca.png'),
       ('클리앙', 'community/icons/clien.png'),
       ('일간베스트', 'community/icons/ilbe.png'),
       ('인스티즈', 'community/icons/instiz.png'),
       ('보배드림', 'community/icons/bobaedream.png'),
       ('웃긴대학', 'community/icons/humoruniv.png'),
       ('오르비', 'community/icons/orbi.png'),
       ('오늘의유머', 'community/icons/todayhumor.png'),
       ('여성시대', 'community/icons/womad.png'),
       ('에브리타임', 'community/icons/everytime.png'),
       ('블라인드', 'community/icons/blind.png'),
       ('Reddit', 'community/icons/reddit.png'),
       ('X', 'community/icons/twitter.png'),
       ('Threads', 'community/icons/threads.png'),
       ('무소속', 'community/icons/independent.png');